### PR TITLE
Format with the current stable rustfmt-preview.

### PR DESCRIPTION
**Pull request by sunfishcode**

### CODE REVIEW

**Comment by yurydelendik** [comment]
check-rustfmt.sh needs to be updated?

**Comment by yurydelendik** [comment]
can you also change Cargo.toml version?

**Comment by sunfishcode** [comment]
In Cranelift, we ended up just folding check-rustfmt.sh into test-all.sh, so I've now synced these scripts to correspond to what we have there. Let me know if there's anything here that doesn't make sense.

And the Cargo.toml version is now updated.

**Comment by sunfishcode** [comment]
I should mention that these changes also correspond to the upstream switch from the "old" rustfmt which was installed via cargo to the "new" rustfmt-preview which is installed via rustup. The names are a little confusing; "rustfmt-preview" is the name of the version that's included in the current stable release.

**Review by yurydelendik — APPROVED** [review]
looks good

**Pull request merged**
