### PR TITLE
Replace some Vecs with boxed slices.

### PR DESCRIPTION
**Pull request by sunfishcode**
Boxed slices aren't resizable, so they don't contain a capacity field,
so they're smaller than Vecs. This change shrinks ParserState from 64
bytes to 56 bytes (on x64).

Inspired by https://github.com/paritytech/parity-wasm/pull/154.

The downsides of this patch are:
 - The syntax for boxed slices sometimes involves things like `&*`, which looks awkward. (The `*` "dereferences" the `Box` to get the object, and the `&` takes a reference to the object.)
 - Users that want to mutate `ParserState` data will have to copy in more cases. But this should be rare.

So I leave it up to you if you want this patch.

### CODE REVIEW

**Comment by yurydelendik** [comment]
Let me also benchmark it first

**Comment by yurydelendik** [comment]
Here is some benchmarks:

##   before
     
    Total Instructions...874,439,524
     
    335,803,544 (38.4%) ???:wasmparser::parser::BinaryReader::read_operator
    -----------------------------------------------------------------------
    281,017,273 (32.1%) ???:_..wasmparser..parser..Parser....a....as..wasmparser..parser..WasmDecoder....a....::read
    -----------------------------------------------------------------------
    87,992,091 (10.1%) ???:wasmparser::parser::BinaryReader::read_var_u32
    -----------------------------------------------------------------------
    69,041,942 (7.9%) ???:core::ptr::drop_in_place
    -----------------------------------------------------------------------
    68,327,655 (7.8%) ???:wasmparser_tanks::main
    -----------------------------------------------------------------------
    27,454,832 (3.1%) ???:wasmparser::parser::BinaryReader::read_var_i32
    -----------------------------------------------------------------------
    1,685,133 (0.2%) ???:wasmparser::parser::BinaryReader::read_local_decl
    -----------------------------------------------------------------------
    1,684,434 (0.2%) ???:wasmparser::parser::Parser::read_function_body
    -----------------------------------------------------------------------
    1,432,620 (0.2%) ???:wasmparser::parser::BinaryReader::read_u32
    -----------------------------------------------------------------------
     
## after
     
    Total Instructions...906,436,388
     
    335,803,544 (37.0%) ???:wasmparser::parser::BinaryReader::read_operator
    -----------------------------------------------------------------------
    291,905,958 (32.2%) ???:_..wasmparser..parser..Parser....a....as..wasmparser..parser..WasmDecoder....a....::read
    -----------------------------------------------------------------------
    90,217,497 (10.0%) ???:core::ptr::drop_in_place
    -----------------------------------------------------------------------
    87,992,091 (9.7%) ???:wasmparser::parser::BinaryReader::read_var_u32
    -----------------------------------------------------------------------
    68,327,655 (7.5%) ???:wasmparser_tanks::main
    -----------------------------------------------------------------------
    27,454,832 (3.0%) ???:wasmparser::parser::BinaryReader::read_var_i32
    -----------------------------------------------------------------------
    1,685,133 (0.2%) ???:wasmparser::parser::BinaryReader::read_local_decl
    -----------------------------------------------------------------------
    1,617,058 (0.2%) ???:wasmparser::parser::Parser::read_function_body
    -----------------------------------------------------------------------
    1,432,620 (0.2%) ???:wasmparser::parser::BinaryReader::read_u32
    ----------------------------------------------------------------------- 

Total executed instructions increased by ~3.5%. I cannot tell if it's a good trade-off yet.

**Comment by sunfishcode** [comment]
@yurydelendik I've now refreshed this patch. On my machine with current Rust stable (1.29.1), this patch shows a reliable 3% speedup decoding a 37MiB wasm file, and with Rust nightly (1.30.0-nightly (ae7fe84e8 2018-09-26)), a 9% speedup.

**Comment by yurydelendik** [comment]
Thanks

**Pull request merged**
